// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CsHostInfo.proto

#include "CsHostInfo.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace CsHostInfo {
constexpr CsHostInfo::CsHostInfo(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : cpuid_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , diskdeviceid_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , macaddress_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct CsHostInfoDefaultTypeInternal {
  constexpr CsHostInfoDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~CsHostInfoDefaultTypeInternal() {}
  union {
    CsHostInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT CsHostInfoDefaultTypeInternal _CsHostInfo_default_instance_;
}  // namespace CsHostInfo
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_CsHostInfo_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_CsHostInfo_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_CsHostInfo_2eproto = nullptr;

const uint32_t TableStruct_CsHostInfo_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::CsHostInfo::CsHostInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::CsHostInfo::CsHostInfo, cpuid_),
  PROTOBUF_FIELD_OFFSET(::CsHostInfo::CsHostInfo, diskdeviceid_),
  PROTOBUF_FIELD_OFFSET(::CsHostInfo::CsHostInfo, macaddress_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::CsHostInfo::CsHostInfo)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::CsHostInfo::_CsHostInfo_default_instance_),
};

const char descriptor_table_protodef_CsHostInfo_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020CsHostInfo.proto\022\nCsHostInfo\"E\n\nCsHost"
  "Info\022\r\n\005cpuId\030\001 \001(\t\022\024\n\014diskDeviceId\030\002 \001("
  "\t\022\022\n\nmacAddress\030\003 \001(\tB*\n\025com.qanydesk.pr"
  "otocolB\017CsHostInfoOuterH\001b\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_CsHostInfo_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_CsHostInfo_2eproto = {
  false, false, 153, descriptor_table_protodef_CsHostInfo_2eproto, "CsHostInfo.proto", 
  &descriptor_table_CsHostInfo_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_CsHostInfo_2eproto::offsets,
  file_level_metadata_CsHostInfo_2eproto, file_level_enum_descriptors_CsHostInfo_2eproto, file_level_service_descriptors_CsHostInfo_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_CsHostInfo_2eproto_getter() {
  return &descriptor_table_CsHostInfo_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_CsHostInfo_2eproto(&descriptor_table_CsHostInfo_2eproto);
namespace CsHostInfo {

// ===================================================================

class CsHostInfo::_Internal {
 public:
};

CsHostInfo::CsHostInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:CsHostInfo.CsHostInfo)
}
CsHostInfo::CsHostInfo(const CsHostInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  cpuid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    cpuid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_cpuid().empty()) {
    cpuid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_cpuid(), 
      GetArenaForAllocation());
  }
  diskdeviceid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    diskdeviceid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_diskdeviceid().empty()) {
    diskdeviceid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_diskdeviceid(), 
      GetArenaForAllocation());
  }
  macaddress_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    macaddress_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_macaddress().empty()) {
    macaddress_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_macaddress(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:CsHostInfo.CsHostInfo)
}

inline void CsHostInfo::SharedCtor() {
cpuid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  cpuid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
diskdeviceid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  diskdeviceid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
macaddress_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  macaddress_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

CsHostInfo::~CsHostInfo() {
  // @@protoc_insertion_point(destructor:CsHostInfo.CsHostInfo)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void CsHostInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  cpuid_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  diskdeviceid_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  macaddress_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void CsHostInfo::ArenaDtor(void* object) {
  CsHostInfo* _this = reinterpret_cast< CsHostInfo* >(object);
  (void)_this;
}
void CsHostInfo::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void CsHostInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void CsHostInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:CsHostInfo.CsHostInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cpuid_.ClearToEmpty();
  diskdeviceid_.ClearToEmpty();
  macaddress_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CsHostInfo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string cpuId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_cpuid();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "CsHostInfo.CsHostInfo.cpuId"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string diskDeviceId = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_diskdeviceid();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "CsHostInfo.CsHostInfo.diskDeviceId"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string macAddress = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_macaddress();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "CsHostInfo.CsHostInfo.macAddress"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CsHostInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CsHostInfo.CsHostInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string cpuId = 1;
  if (!this->_internal_cpuid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_cpuid().data(), static_cast<int>(this->_internal_cpuid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "CsHostInfo.CsHostInfo.cpuId");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_cpuid(), target);
  }

  // string diskDeviceId = 2;
  if (!this->_internal_diskdeviceid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_diskdeviceid().data(), static_cast<int>(this->_internal_diskdeviceid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "CsHostInfo.CsHostInfo.diskDeviceId");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_diskdeviceid(), target);
  }

  // string macAddress = 3;
  if (!this->_internal_macaddress().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_macaddress().data(), static_cast<int>(this->_internal_macaddress().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "CsHostInfo.CsHostInfo.macAddress");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_macaddress(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CsHostInfo.CsHostInfo)
  return target;
}

size_t CsHostInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CsHostInfo.CsHostInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string cpuId = 1;
  if (!this->_internal_cpuid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_cpuid());
  }

  // string diskDeviceId = 2;
  if (!this->_internal_diskdeviceid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_diskdeviceid());
  }

  // string macAddress = 3;
  if (!this->_internal_macaddress().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_macaddress());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CsHostInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    CsHostInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CsHostInfo::GetClassData() const { return &_class_data_; }

void CsHostInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<CsHostInfo *>(to)->MergeFrom(
      static_cast<const CsHostInfo &>(from));
}


void CsHostInfo::MergeFrom(const CsHostInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CsHostInfo.CsHostInfo)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_cpuid().empty()) {
    _internal_set_cpuid(from._internal_cpuid());
  }
  if (!from._internal_diskdeviceid().empty()) {
    _internal_set_diskdeviceid(from._internal_diskdeviceid());
  }
  if (!from._internal_macaddress().empty()) {
    _internal_set_macaddress(from._internal_macaddress());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CsHostInfo::CopyFrom(const CsHostInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CsHostInfo.CsHostInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CsHostInfo::IsInitialized() const {
  return true;
}

void CsHostInfo::InternalSwap(CsHostInfo* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &cpuid_, lhs_arena,
      &other->cpuid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &diskdeviceid_, lhs_arena,
      &other->diskdeviceid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &macaddress_, lhs_arena,
      &other->macaddress_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata CsHostInfo::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_CsHostInfo_2eproto_getter, &descriptor_table_CsHostInfo_2eproto_once,
      file_level_metadata_CsHostInfo_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace CsHostInfo
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::CsHostInfo::CsHostInfo* Arena::CreateMaybeMessage< ::CsHostInfo::CsHostInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CsHostInfo::CsHostInfo >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
