// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

package com.qanydesk.protocol;

public final class ProtocolOuter {
  private ProtocolOuter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protocol.Protocol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>.Protocol.CsHostInfo csHostInfo = 2;</code>
     * @return Whether the csHostInfo field is set.
     */
    boolean hasCsHostInfo();
    /**
     * <code>.Protocol.CsHostInfo csHostInfo = 2;</code>
     * @return The csHostInfo.
     */
    com.qanydesk.protocol.ProtocolOuter.CsHostInfo getCsHostInfo();
    /**
     * <code>.Protocol.CsHostInfo csHostInfo = 2;</code>
     */
    com.qanydesk.protocol.ProtocolOuter.CsHostInfoOrBuilder getCsHostInfoOrBuilder();

    /**
     * <code>.Protocol.ScReplyInfo scReplyInfo = 3;</code>
     * @return Whether the scReplyInfo field is set.
     */
    boolean hasScReplyInfo();
    /**
     * <code>.Protocol.ScReplyInfo scReplyInfo = 3;</code>
     * @return The scReplyInfo.
     */
    com.qanydesk.protocol.ProtocolOuter.ScReplyInfo getScReplyInfo();
    /**
     * <code>.Protocol.ScReplyInfo scReplyInfo = 3;</code>
     */
    com.qanydesk.protocol.ProtocolOuter.ScReplyInfoOrBuilder getScReplyInfoOrBuilder();

    public com.qanydesk.protocol.ProtocolOuter.Protocol.BodyCase getBodyCase();
  }
  /**
   * <pre>
   * C++的头文件名取第一个message名
   * </pre>
   *
   * Protobuf type {@code Protocol.Protocol}
   */
  public static final class Protocol extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protocol.Protocol)
      ProtocolOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Protocol.newBuilder() to construct.
    private Protocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Protocol() {
      type_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Protocol();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Protocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 18: {
              com.qanydesk.protocol.ProtocolOuter.CsHostInfo.Builder subBuilder = null;
              if (bodyCase_ == 2) {
                subBuilder = ((com.qanydesk.protocol.ProtocolOuter.CsHostInfo) body_).toBuilder();
              }
              body_ =
                  input.readMessage(com.qanydesk.protocol.ProtocolOuter.CsHostInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.qanydesk.protocol.ProtocolOuter.CsHostInfo) body_);
                body_ = subBuilder.buildPartial();
              }
              bodyCase_ = 2;
              break;
            }
            case 26: {
              com.qanydesk.protocol.ProtocolOuter.ScReplyInfo.Builder subBuilder = null;
              if (bodyCase_ == 3) {
                subBuilder = ((com.qanydesk.protocol.ProtocolOuter.ScReplyInfo) body_).toBuilder();
              }
              body_ =
                  input.readMessage(com.qanydesk.protocol.ProtocolOuter.ScReplyInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.qanydesk.protocol.ProtocolOuter.ScReplyInfo) body_);
                body_ = subBuilder.buildPartial();
              }
              bodyCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qanydesk.protocol.ProtocolOuter.internal_static_Protocol_Protocol_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qanydesk.protocol.ProtocolOuter.internal_static_Protocol_Protocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qanydesk.protocol.ProtocolOuter.Protocol.class, com.qanydesk.protocol.ProtocolOuter.Protocol.Builder.class);
    }

    private int bodyCase_ = 0;
    private java.lang.Object body_;
    public enum BodyCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      CSHOSTINFO(2),
      SCREPLYINFO(3),
      BODY_NOT_SET(0);
      private final int value;
      private BodyCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static BodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static BodyCase forNumber(int value) {
        switch (value) {
          case 2: return CSHOSTINFO;
          case 3: return SCREPLYINFO;
          case 0: return BODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public BodyCase
    getBodyCase() {
      return BodyCase.forNumber(
          bodyCase_);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object type_;
    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CSHOSTINFO_FIELD_NUMBER = 2;
    /**
     * <code>.Protocol.CsHostInfo csHostInfo = 2;</code>
     * @return Whether the csHostInfo field is set.
     */
    @java.lang.Override
    public boolean hasCsHostInfo() {
      return bodyCase_ == 2;
    }
    /**
     * <code>.Protocol.CsHostInfo csHostInfo = 2;</code>
     * @return The csHostInfo.
     */
    @java.lang.Override
    public com.qanydesk.protocol.ProtocolOuter.CsHostInfo getCsHostInfo() {
      if (bodyCase_ == 2) {
         return (com.qanydesk.protocol.ProtocolOuter.CsHostInfo) body_;
      }
      return com.qanydesk.protocol.ProtocolOuter.CsHostInfo.getDefaultInstance();
    }
    /**
     * <code>.Protocol.CsHostInfo csHostInfo = 2;</code>
     */
    @java.lang.Override
    public com.qanydesk.protocol.ProtocolOuter.CsHostInfoOrBuilder getCsHostInfoOrBuilder() {
      if (bodyCase_ == 2) {
         return (com.qanydesk.protocol.ProtocolOuter.CsHostInfo) body_;
      }
      return com.qanydesk.protocol.ProtocolOuter.CsHostInfo.getDefaultInstance();
    }

    public static final int SCREPLYINFO_FIELD_NUMBER = 3;
    /**
     * <code>.Protocol.ScReplyInfo scReplyInfo = 3;</code>
     * @return Whether the scReplyInfo field is set.
     */
    @java.lang.Override
    public boolean hasScReplyInfo() {
      return bodyCase_ == 3;
    }
    /**
     * <code>.Protocol.ScReplyInfo scReplyInfo = 3;</code>
     * @return The scReplyInfo.
     */
    @java.lang.Override
    public com.qanydesk.protocol.ProtocolOuter.ScReplyInfo getScReplyInfo() {
      if (bodyCase_ == 3) {
         return (com.qanydesk.protocol.ProtocolOuter.ScReplyInfo) body_;
      }
      return com.qanydesk.protocol.ProtocolOuter.ScReplyInfo.getDefaultInstance();
    }
    /**
     * <code>.Protocol.ScReplyInfo scReplyInfo = 3;</code>
     */
    @java.lang.Override
    public com.qanydesk.protocol.ProtocolOuter.ScReplyInfoOrBuilder getScReplyInfoOrBuilder() {
      if (bodyCase_ == 3) {
         return (com.qanydesk.protocol.ProtocolOuter.ScReplyInfo) body_;
      }
      return com.qanydesk.protocol.ProtocolOuter.ScReplyInfo.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (bodyCase_ == 2) {
        output.writeMessage(2, (com.qanydesk.protocol.ProtocolOuter.CsHostInfo) body_);
      }
      if (bodyCase_ == 3) {
        output.writeMessage(3, (com.qanydesk.protocol.ProtocolOuter.ScReplyInfo) body_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (bodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.qanydesk.protocol.ProtocolOuter.CsHostInfo) body_);
      }
      if (bodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.qanydesk.protocol.ProtocolOuter.ScReplyInfo) body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qanydesk.protocol.ProtocolOuter.Protocol)) {
        return super.equals(obj);
      }
      com.qanydesk.protocol.ProtocolOuter.Protocol other = (com.qanydesk.protocol.ProtocolOuter.Protocol) obj;

      if (!getType()
          .equals(other.getType())) return false;
      if (!getBodyCase().equals(other.getBodyCase())) return false;
      switch (bodyCase_) {
        case 2:
          if (!getCsHostInfo()
              .equals(other.getCsHostInfo())) return false;
          break;
        case 3:
          if (!getScReplyInfo()
              .equals(other.getScReplyInfo())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      switch (bodyCase_) {
        case 2:
          hash = (37 * hash) + CSHOSTINFO_FIELD_NUMBER;
          hash = (53 * hash) + getCsHostInfo().hashCode();
          break;
        case 3:
          hash = (37 * hash) + SCREPLYINFO_FIELD_NUMBER;
          hash = (53 * hash) + getScReplyInfo().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qanydesk.protocol.ProtocolOuter.Protocol parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qanydesk.protocol.ProtocolOuter.Protocol parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qanydesk.protocol.ProtocolOuter.Protocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qanydesk.protocol.ProtocolOuter.Protocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qanydesk.protocol.ProtocolOuter.Protocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qanydesk.protocol.ProtocolOuter.Protocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qanydesk.protocol.ProtocolOuter.Protocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qanydesk.protocol.ProtocolOuter.Protocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qanydesk.protocol.ProtocolOuter.Protocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qanydesk.protocol.ProtocolOuter.Protocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qanydesk.protocol.ProtocolOuter.Protocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qanydesk.protocol.ProtocolOuter.Protocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qanydesk.protocol.ProtocolOuter.Protocol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * C++的头文件名取第一个message名
     * </pre>
     *
     * Protobuf type {@code Protocol.Protocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protocol.Protocol)
        com.qanydesk.protocol.ProtocolOuter.ProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qanydesk.protocol.ProtocolOuter.internal_static_Protocol_Protocol_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qanydesk.protocol.ProtocolOuter.internal_static_Protocol_Protocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qanydesk.protocol.ProtocolOuter.Protocol.class, com.qanydesk.protocol.ProtocolOuter.Protocol.Builder.class);
      }

      // Construct using com.qanydesk.protocol.ProtocolOuter.Protocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = "";

        bodyCase_ = 0;
        body_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qanydesk.protocol.ProtocolOuter.internal_static_Protocol_Protocol_descriptor;
      }

      @java.lang.Override
      public com.qanydesk.protocol.ProtocolOuter.Protocol getDefaultInstanceForType() {
        return com.qanydesk.protocol.ProtocolOuter.Protocol.getDefaultInstance();
      }

      @java.lang.Override
      public com.qanydesk.protocol.ProtocolOuter.Protocol build() {
        com.qanydesk.protocol.ProtocolOuter.Protocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.qanydesk.protocol.ProtocolOuter.Protocol buildPartial() {
        com.qanydesk.protocol.ProtocolOuter.Protocol result = new com.qanydesk.protocol.ProtocolOuter.Protocol(this);
        result.type_ = type_;
        if (bodyCase_ == 2) {
          if (csHostInfoBuilder_ == null) {
            result.body_ = body_;
          } else {
            result.body_ = csHostInfoBuilder_.build();
          }
        }
        if (bodyCase_ == 3) {
          if (scReplyInfoBuilder_ == null) {
            result.body_ = body_;
          } else {
            result.body_ = scReplyInfoBuilder_.build();
          }
        }
        result.bodyCase_ = bodyCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qanydesk.protocol.ProtocolOuter.Protocol) {
          return mergeFrom((com.qanydesk.protocol.ProtocolOuter.Protocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qanydesk.protocol.ProtocolOuter.Protocol other) {
        if (other == com.qanydesk.protocol.ProtocolOuter.Protocol.getDefaultInstance()) return this;
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        switch (other.getBodyCase()) {
          case CSHOSTINFO: {
            mergeCsHostInfo(other.getCsHostInfo());
            break;
          }
          case SCREPLYINFO: {
            mergeScReplyInfo(other.getScReplyInfo());
            break;
          }
          case BODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qanydesk.protocol.ProtocolOuter.Protocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qanydesk.protocol.ProtocolOuter.Protocol) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bodyCase_ = 0;
      private java.lang.Object body_;
      public BodyCase
          getBodyCase() {
        return BodyCase.forNumber(
            bodyCase_);
      }

      public Builder clearBody() {
        bodyCase_ = 0;
        body_ = null;
        onChanged();
        return this;
      }


      private java.lang.Object type_ = "";
      /**
       * <code>string type = 1;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.qanydesk.protocol.ProtocolOuter.CsHostInfo, com.qanydesk.protocol.ProtocolOuter.CsHostInfo.Builder, com.qanydesk.protocol.ProtocolOuter.CsHostInfoOrBuilder> csHostInfoBuilder_;
      /**
       * <code>.Protocol.CsHostInfo csHostInfo = 2;</code>
       * @return Whether the csHostInfo field is set.
       */
      @java.lang.Override
      public boolean hasCsHostInfo() {
        return bodyCase_ == 2;
      }
      /**
       * <code>.Protocol.CsHostInfo csHostInfo = 2;</code>
       * @return The csHostInfo.
       */
      @java.lang.Override
      public com.qanydesk.protocol.ProtocolOuter.CsHostInfo getCsHostInfo() {
        if (csHostInfoBuilder_ == null) {
          if (bodyCase_ == 2) {
            return (com.qanydesk.protocol.ProtocolOuter.CsHostInfo) body_;
          }
          return com.qanydesk.protocol.ProtocolOuter.CsHostInfo.getDefaultInstance();
        } else {
          if (bodyCase_ == 2) {
            return csHostInfoBuilder_.getMessage();
          }
          return com.qanydesk.protocol.ProtocolOuter.CsHostInfo.getDefaultInstance();
        }
      }
      /**
       * <code>.Protocol.CsHostInfo csHostInfo = 2;</code>
       */
      public Builder setCsHostInfo(com.qanydesk.protocol.ProtocolOuter.CsHostInfo value) {
        if (csHostInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          csHostInfoBuilder_.setMessage(value);
        }
        bodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Protocol.CsHostInfo csHostInfo = 2;</code>
       */
      public Builder setCsHostInfo(
          com.qanydesk.protocol.ProtocolOuter.CsHostInfo.Builder builderForValue) {
        if (csHostInfoBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          csHostInfoBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Protocol.CsHostInfo csHostInfo = 2;</code>
       */
      public Builder mergeCsHostInfo(com.qanydesk.protocol.ProtocolOuter.CsHostInfo value) {
        if (csHostInfoBuilder_ == null) {
          if (bodyCase_ == 2 &&
              body_ != com.qanydesk.protocol.ProtocolOuter.CsHostInfo.getDefaultInstance()) {
            body_ = com.qanydesk.protocol.ProtocolOuter.CsHostInfo.newBuilder((com.qanydesk.protocol.ProtocolOuter.CsHostInfo) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 2) {
            csHostInfoBuilder_.mergeFrom(value);
          }
          csHostInfoBuilder_.setMessage(value);
        }
        bodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Protocol.CsHostInfo csHostInfo = 2;</code>
       */
      public Builder clearCsHostInfo() {
        if (csHostInfoBuilder_ == null) {
          if (bodyCase_ == 2) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 2) {
            bodyCase_ = 0;
            body_ = null;
          }
          csHostInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Protocol.CsHostInfo csHostInfo = 2;</code>
       */
      public com.qanydesk.protocol.ProtocolOuter.CsHostInfo.Builder getCsHostInfoBuilder() {
        return getCsHostInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.Protocol.CsHostInfo csHostInfo = 2;</code>
       */
      @java.lang.Override
      public com.qanydesk.protocol.ProtocolOuter.CsHostInfoOrBuilder getCsHostInfoOrBuilder() {
        if ((bodyCase_ == 2) && (csHostInfoBuilder_ != null)) {
          return csHostInfoBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 2) {
            return (com.qanydesk.protocol.ProtocolOuter.CsHostInfo) body_;
          }
          return com.qanydesk.protocol.ProtocolOuter.CsHostInfo.getDefaultInstance();
        }
      }
      /**
       * <code>.Protocol.CsHostInfo csHostInfo = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.qanydesk.protocol.ProtocolOuter.CsHostInfo, com.qanydesk.protocol.ProtocolOuter.CsHostInfo.Builder, com.qanydesk.protocol.ProtocolOuter.CsHostInfoOrBuilder> 
          getCsHostInfoFieldBuilder() {
        if (csHostInfoBuilder_ == null) {
          if (!(bodyCase_ == 2)) {
            body_ = com.qanydesk.protocol.ProtocolOuter.CsHostInfo.getDefaultInstance();
          }
          csHostInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.qanydesk.protocol.ProtocolOuter.CsHostInfo, com.qanydesk.protocol.ProtocolOuter.CsHostInfo.Builder, com.qanydesk.protocol.ProtocolOuter.CsHostInfoOrBuilder>(
                  (com.qanydesk.protocol.ProtocolOuter.CsHostInfo) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 2;
        onChanged();;
        return csHostInfoBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.qanydesk.protocol.ProtocolOuter.ScReplyInfo, com.qanydesk.protocol.ProtocolOuter.ScReplyInfo.Builder, com.qanydesk.protocol.ProtocolOuter.ScReplyInfoOrBuilder> scReplyInfoBuilder_;
      /**
       * <code>.Protocol.ScReplyInfo scReplyInfo = 3;</code>
       * @return Whether the scReplyInfo field is set.
       */
      @java.lang.Override
      public boolean hasScReplyInfo() {
        return bodyCase_ == 3;
      }
      /**
       * <code>.Protocol.ScReplyInfo scReplyInfo = 3;</code>
       * @return The scReplyInfo.
       */
      @java.lang.Override
      public com.qanydesk.protocol.ProtocolOuter.ScReplyInfo getScReplyInfo() {
        if (scReplyInfoBuilder_ == null) {
          if (bodyCase_ == 3) {
            return (com.qanydesk.protocol.ProtocolOuter.ScReplyInfo) body_;
          }
          return com.qanydesk.protocol.ProtocolOuter.ScReplyInfo.getDefaultInstance();
        } else {
          if (bodyCase_ == 3) {
            return scReplyInfoBuilder_.getMessage();
          }
          return com.qanydesk.protocol.ProtocolOuter.ScReplyInfo.getDefaultInstance();
        }
      }
      /**
       * <code>.Protocol.ScReplyInfo scReplyInfo = 3;</code>
       */
      public Builder setScReplyInfo(com.qanydesk.protocol.ProtocolOuter.ScReplyInfo value) {
        if (scReplyInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          scReplyInfoBuilder_.setMessage(value);
        }
        bodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Protocol.ScReplyInfo scReplyInfo = 3;</code>
       */
      public Builder setScReplyInfo(
          com.qanydesk.protocol.ProtocolOuter.ScReplyInfo.Builder builderForValue) {
        if (scReplyInfoBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          scReplyInfoBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Protocol.ScReplyInfo scReplyInfo = 3;</code>
       */
      public Builder mergeScReplyInfo(com.qanydesk.protocol.ProtocolOuter.ScReplyInfo value) {
        if (scReplyInfoBuilder_ == null) {
          if (bodyCase_ == 3 &&
              body_ != com.qanydesk.protocol.ProtocolOuter.ScReplyInfo.getDefaultInstance()) {
            body_ = com.qanydesk.protocol.ProtocolOuter.ScReplyInfo.newBuilder((com.qanydesk.protocol.ProtocolOuter.ScReplyInfo) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 3) {
            scReplyInfoBuilder_.mergeFrom(value);
          }
          scReplyInfoBuilder_.setMessage(value);
        }
        bodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Protocol.ScReplyInfo scReplyInfo = 3;</code>
       */
      public Builder clearScReplyInfo() {
        if (scReplyInfoBuilder_ == null) {
          if (bodyCase_ == 3) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 3) {
            bodyCase_ = 0;
            body_ = null;
          }
          scReplyInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Protocol.ScReplyInfo scReplyInfo = 3;</code>
       */
      public com.qanydesk.protocol.ProtocolOuter.ScReplyInfo.Builder getScReplyInfoBuilder() {
        return getScReplyInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.Protocol.ScReplyInfo scReplyInfo = 3;</code>
       */
      @java.lang.Override
      public com.qanydesk.protocol.ProtocolOuter.ScReplyInfoOrBuilder getScReplyInfoOrBuilder() {
        if ((bodyCase_ == 3) && (scReplyInfoBuilder_ != null)) {
          return scReplyInfoBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 3) {
            return (com.qanydesk.protocol.ProtocolOuter.ScReplyInfo) body_;
          }
          return com.qanydesk.protocol.ProtocolOuter.ScReplyInfo.getDefaultInstance();
        }
      }
      /**
       * <code>.Protocol.ScReplyInfo scReplyInfo = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.qanydesk.protocol.ProtocolOuter.ScReplyInfo, com.qanydesk.protocol.ProtocolOuter.ScReplyInfo.Builder, com.qanydesk.protocol.ProtocolOuter.ScReplyInfoOrBuilder> 
          getScReplyInfoFieldBuilder() {
        if (scReplyInfoBuilder_ == null) {
          if (!(bodyCase_ == 3)) {
            body_ = com.qanydesk.protocol.ProtocolOuter.ScReplyInfo.getDefaultInstance();
          }
          scReplyInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.qanydesk.protocol.ProtocolOuter.ScReplyInfo, com.qanydesk.protocol.ProtocolOuter.ScReplyInfo.Builder, com.qanydesk.protocol.ProtocolOuter.ScReplyInfoOrBuilder>(
                  (com.qanydesk.protocol.ProtocolOuter.ScReplyInfo) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 3;
        onChanged();;
        return scReplyInfoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protocol.Protocol)
    }

    // @@protoc_insertion_point(class_scope:Protocol.Protocol)
    private static final com.qanydesk.protocol.ProtocolOuter.Protocol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qanydesk.protocol.ProtocolOuter.Protocol();
    }

    public static com.qanydesk.protocol.ProtocolOuter.Protocol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Protocol>
        PARSER = new com.google.protobuf.AbstractParser<Protocol>() {
      @java.lang.Override
      public Protocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Protocol(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Protocol> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Protocol> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.qanydesk.protocol.ProtocolOuter.Protocol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CsHostInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protocol.CsHostInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string cpuId = 1;</code>
     * @return The cpuId.
     */
    java.lang.String getCpuId();
    /**
     * <code>string cpuId = 1;</code>
     * @return The bytes for cpuId.
     */
    com.google.protobuf.ByteString
        getCpuIdBytes();

    /**
     * <pre>
     * 硬盘ID
     * </pre>
     *
     * <code>string diskDeviceId = 2;</code>
     * @return The diskDeviceId.
     */
    java.lang.String getDiskDeviceId();
    /**
     * <pre>
     * 硬盘ID
     * </pre>
     *
     * <code>string diskDeviceId = 2;</code>
     * @return The bytes for diskDeviceId.
     */
    com.google.protobuf.ByteString
        getDiskDeviceIdBytes();

    /**
     * <code>string macAddress = 3;</code>
     * @return The macAddress.
     */
    java.lang.String getMacAddress();
    /**
     * <code>string macAddress = 3;</code>
     * @return The bytes for macAddress.
     */
    com.google.protobuf.ByteString
        getMacAddressBytes();
  }
  /**
   * Protobuf type {@code Protocol.CsHostInfo}
   */
  public static final class CsHostInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protocol.CsHostInfo)
      CsHostInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CsHostInfo.newBuilder() to construct.
    private CsHostInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CsHostInfo() {
      cpuId_ = "";
      diskDeviceId_ = "";
      macAddress_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CsHostInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CsHostInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              cpuId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              diskDeviceId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              macAddress_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qanydesk.protocol.ProtocolOuter.internal_static_Protocol_CsHostInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qanydesk.protocol.ProtocolOuter.internal_static_Protocol_CsHostInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qanydesk.protocol.ProtocolOuter.CsHostInfo.class, com.qanydesk.protocol.ProtocolOuter.CsHostInfo.Builder.class);
    }

    public static final int CPUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object cpuId_;
    /**
     * <code>string cpuId = 1;</code>
     * @return The cpuId.
     */
    @java.lang.Override
    public java.lang.String getCpuId() {
      java.lang.Object ref = cpuId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cpuId_ = s;
        return s;
      }
    }
    /**
     * <code>string cpuId = 1;</code>
     * @return The bytes for cpuId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCpuIdBytes() {
      java.lang.Object ref = cpuId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cpuId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DISKDEVICEID_FIELD_NUMBER = 2;
    private volatile java.lang.Object diskDeviceId_;
    /**
     * <pre>
     * 硬盘ID
     * </pre>
     *
     * <code>string diskDeviceId = 2;</code>
     * @return The diskDeviceId.
     */
    @java.lang.Override
    public java.lang.String getDiskDeviceId() {
      java.lang.Object ref = diskDeviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        diskDeviceId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 硬盘ID
     * </pre>
     *
     * <code>string diskDeviceId = 2;</code>
     * @return The bytes for diskDeviceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDiskDeviceIdBytes() {
      java.lang.Object ref = diskDeviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        diskDeviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MACADDRESS_FIELD_NUMBER = 3;
    private volatile java.lang.Object macAddress_;
    /**
     * <code>string macAddress = 3;</code>
     * @return The macAddress.
     */
    @java.lang.Override
    public java.lang.String getMacAddress() {
      java.lang.Object ref = macAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        macAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string macAddress = 3;</code>
     * @return The bytes for macAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMacAddressBytes() {
      java.lang.Object ref = macAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        macAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cpuId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cpuId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(diskDeviceId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, diskDeviceId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(macAddress_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, macAddress_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cpuId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cpuId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(diskDeviceId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, diskDeviceId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(macAddress_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, macAddress_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qanydesk.protocol.ProtocolOuter.CsHostInfo)) {
        return super.equals(obj);
      }
      com.qanydesk.protocol.ProtocolOuter.CsHostInfo other = (com.qanydesk.protocol.ProtocolOuter.CsHostInfo) obj;

      if (!getCpuId()
          .equals(other.getCpuId())) return false;
      if (!getDiskDeviceId()
          .equals(other.getDiskDeviceId())) return false;
      if (!getMacAddress()
          .equals(other.getMacAddress())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CPUID_FIELD_NUMBER;
      hash = (53 * hash) + getCpuId().hashCode();
      hash = (37 * hash) + DISKDEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getDiskDeviceId().hashCode();
      hash = (37 * hash) + MACADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getMacAddress().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qanydesk.protocol.ProtocolOuter.CsHostInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qanydesk.protocol.ProtocolOuter.CsHostInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qanydesk.protocol.ProtocolOuter.CsHostInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qanydesk.protocol.ProtocolOuter.CsHostInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qanydesk.protocol.ProtocolOuter.CsHostInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qanydesk.protocol.ProtocolOuter.CsHostInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qanydesk.protocol.ProtocolOuter.CsHostInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qanydesk.protocol.ProtocolOuter.CsHostInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qanydesk.protocol.ProtocolOuter.CsHostInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qanydesk.protocol.ProtocolOuter.CsHostInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qanydesk.protocol.ProtocolOuter.CsHostInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qanydesk.protocol.ProtocolOuter.CsHostInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qanydesk.protocol.ProtocolOuter.CsHostInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Protocol.CsHostInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protocol.CsHostInfo)
        com.qanydesk.protocol.ProtocolOuter.CsHostInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qanydesk.protocol.ProtocolOuter.internal_static_Protocol_CsHostInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qanydesk.protocol.ProtocolOuter.internal_static_Protocol_CsHostInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qanydesk.protocol.ProtocolOuter.CsHostInfo.class, com.qanydesk.protocol.ProtocolOuter.CsHostInfo.Builder.class);
      }

      // Construct using com.qanydesk.protocol.ProtocolOuter.CsHostInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cpuId_ = "";

        diskDeviceId_ = "";

        macAddress_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qanydesk.protocol.ProtocolOuter.internal_static_Protocol_CsHostInfo_descriptor;
      }

      @java.lang.Override
      public com.qanydesk.protocol.ProtocolOuter.CsHostInfo getDefaultInstanceForType() {
        return com.qanydesk.protocol.ProtocolOuter.CsHostInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.qanydesk.protocol.ProtocolOuter.CsHostInfo build() {
        com.qanydesk.protocol.ProtocolOuter.CsHostInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.qanydesk.protocol.ProtocolOuter.CsHostInfo buildPartial() {
        com.qanydesk.protocol.ProtocolOuter.CsHostInfo result = new com.qanydesk.protocol.ProtocolOuter.CsHostInfo(this);
        result.cpuId_ = cpuId_;
        result.diskDeviceId_ = diskDeviceId_;
        result.macAddress_ = macAddress_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qanydesk.protocol.ProtocolOuter.CsHostInfo) {
          return mergeFrom((com.qanydesk.protocol.ProtocolOuter.CsHostInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qanydesk.protocol.ProtocolOuter.CsHostInfo other) {
        if (other == com.qanydesk.protocol.ProtocolOuter.CsHostInfo.getDefaultInstance()) return this;
        if (!other.getCpuId().isEmpty()) {
          cpuId_ = other.cpuId_;
          onChanged();
        }
        if (!other.getDiskDeviceId().isEmpty()) {
          diskDeviceId_ = other.diskDeviceId_;
          onChanged();
        }
        if (!other.getMacAddress().isEmpty()) {
          macAddress_ = other.macAddress_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qanydesk.protocol.ProtocolOuter.CsHostInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qanydesk.protocol.ProtocolOuter.CsHostInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object cpuId_ = "";
      /**
       * <code>string cpuId = 1;</code>
       * @return The cpuId.
       */
      public java.lang.String getCpuId() {
        java.lang.Object ref = cpuId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cpuId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cpuId = 1;</code>
       * @return The bytes for cpuId.
       */
      public com.google.protobuf.ByteString
          getCpuIdBytes() {
        java.lang.Object ref = cpuId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cpuId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cpuId = 1;</code>
       * @param value The cpuId to set.
       * @return This builder for chaining.
       */
      public Builder setCpuId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cpuId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cpuId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCpuId() {
        
        cpuId_ = getDefaultInstance().getCpuId();
        onChanged();
        return this;
      }
      /**
       * <code>string cpuId = 1;</code>
       * @param value The bytes for cpuId to set.
       * @return This builder for chaining.
       */
      public Builder setCpuIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cpuId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object diskDeviceId_ = "";
      /**
       * <pre>
       * 硬盘ID
       * </pre>
       *
       * <code>string diskDeviceId = 2;</code>
       * @return The diskDeviceId.
       */
      public java.lang.String getDiskDeviceId() {
        java.lang.Object ref = diskDeviceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          diskDeviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 硬盘ID
       * </pre>
       *
       * <code>string diskDeviceId = 2;</code>
       * @return The bytes for diskDeviceId.
       */
      public com.google.protobuf.ByteString
          getDiskDeviceIdBytes() {
        java.lang.Object ref = diskDeviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          diskDeviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 硬盘ID
       * </pre>
       *
       * <code>string diskDeviceId = 2;</code>
       * @param value The diskDeviceId to set.
       * @return This builder for chaining.
       */
      public Builder setDiskDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        diskDeviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 硬盘ID
       * </pre>
       *
       * <code>string diskDeviceId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDiskDeviceId() {
        
        diskDeviceId_ = getDefaultInstance().getDiskDeviceId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 硬盘ID
       * </pre>
       *
       * <code>string diskDeviceId = 2;</code>
       * @param value The bytes for diskDeviceId to set.
       * @return This builder for chaining.
       */
      public Builder setDiskDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        diskDeviceId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object macAddress_ = "";
      /**
       * <code>string macAddress = 3;</code>
       * @return The macAddress.
       */
      public java.lang.String getMacAddress() {
        java.lang.Object ref = macAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          macAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string macAddress = 3;</code>
       * @return The bytes for macAddress.
       */
      public com.google.protobuf.ByteString
          getMacAddressBytes() {
        java.lang.Object ref = macAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          macAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string macAddress = 3;</code>
       * @param value The macAddress to set.
       * @return This builder for chaining.
       */
      public Builder setMacAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        macAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string macAddress = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMacAddress() {
        
        macAddress_ = getDefaultInstance().getMacAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string macAddress = 3;</code>
       * @param value The bytes for macAddress to set.
       * @return This builder for chaining.
       */
      public Builder setMacAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        macAddress_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protocol.CsHostInfo)
    }

    // @@protoc_insertion_point(class_scope:Protocol.CsHostInfo)
    private static final com.qanydesk.protocol.ProtocolOuter.CsHostInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qanydesk.protocol.ProtocolOuter.CsHostInfo();
    }

    public static com.qanydesk.protocol.ProtocolOuter.CsHostInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CsHostInfo>
        PARSER = new com.google.protobuf.AbstractParser<CsHostInfo>() {
      @java.lang.Override
      public CsHostInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CsHostInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CsHostInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CsHostInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.qanydesk.protocol.ProtocolOuter.CsHostInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ScReplyInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protocol.ScReplyInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <code>string registerId = 2;</code>
     * @return The registerId.
     */
    java.lang.String getRegisterId();
    /**
     * <code>string registerId = 2;</code>
     * @return The bytes for registerId.
     */
    com.google.protobuf.ByteString
        getRegisterIdBytes();
  }
  /**
   * <pre>
   * 注册信息
   * </pre>
   *
   * Protobuf type {@code Protocol.ScReplyInfo}
   */
  public static final class ScReplyInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protocol.ScReplyInfo)
      ScReplyInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ScReplyInfo.newBuilder() to construct.
    private ScReplyInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ScReplyInfo() {
      registerId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ScReplyInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ScReplyInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              success_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              registerId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qanydesk.protocol.ProtocolOuter.internal_static_Protocol_ScReplyInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qanydesk.protocol.ProtocolOuter.internal_static_Protocol_ScReplyInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qanydesk.protocol.ProtocolOuter.ScReplyInfo.class, com.qanydesk.protocol.ProtocolOuter.ScReplyInfo.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }

    public static final int REGISTERID_FIELD_NUMBER = 2;
    private volatile java.lang.Object registerId_;
    /**
     * <code>string registerId = 2;</code>
     * @return The registerId.
     */
    @java.lang.Override
    public java.lang.String getRegisterId() {
      java.lang.Object ref = registerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        registerId_ = s;
        return s;
      }
    }
    /**
     * <code>string registerId = 2;</code>
     * @return The bytes for registerId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRegisterIdBytes() {
      java.lang.Object ref = registerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        registerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(registerId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, registerId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(registerId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, registerId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qanydesk.protocol.ProtocolOuter.ScReplyInfo)) {
        return super.equals(obj);
      }
      com.qanydesk.protocol.ProtocolOuter.ScReplyInfo other = (com.qanydesk.protocol.ProtocolOuter.ScReplyInfo) obj;

      if (getSuccess()
          != other.getSuccess()) return false;
      if (!getRegisterId()
          .equals(other.getRegisterId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + REGISTERID_FIELD_NUMBER;
      hash = (53 * hash) + getRegisterId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qanydesk.protocol.ProtocolOuter.ScReplyInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qanydesk.protocol.ProtocolOuter.ScReplyInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qanydesk.protocol.ProtocolOuter.ScReplyInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qanydesk.protocol.ProtocolOuter.ScReplyInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qanydesk.protocol.ProtocolOuter.ScReplyInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qanydesk.protocol.ProtocolOuter.ScReplyInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qanydesk.protocol.ProtocolOuter.ScReplyInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qanydesk.protocol.ProtocolOuter.ScReplyInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qanydesk.protocol.ProtocolOuter.ScReplyInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qanydesk.protocol.ProtocolOuter.ScReplyInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qanydesk.protocol.ProtocolOuter.ScReplyInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qanydesk.protocol.ProtocolOuter.ScReplyInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qanydesk.protocol.ProtocolOuter.ScReplyInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 注册信息
     * </pre>
     *
     * Protobuf type {@code Protocol.ScReplyInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protocol.ScReplyInfo)
        com.qanydesk.protocol.ProtocolOuter.ScReplyInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qanydesk.protocol.ProtocolOuter.internal_static_Protocol_ScReplyInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qanydesk.protocol.ProtocolOuter.internal_static_Protocol_ScReplyInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qanydesk.protocol.ProtocolOuter.ScReplyInfo.class, com.qanydesk.protocol.ProtocolOuter.ScReplyInfo.Builder.class);
      }

      // Construct using com.qanydesk.protocol.ProtocolOuter.ScReplyInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        success_ = false;

        registerId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qanydesk.protocol.ProtocolOuter.internal_static_Protocol_ScReplyInfo_descriptor;
      }

      @java.lang.Override
      public com.qanydesk.protocol.ProtocolOuter.ScReplyInfo getDefaultInstanceForType() {
        return com.qanydesk.protocol.ProtocolOuter.ScReplyInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.qanydesk.protocol.ProtocolOuter.ScReplyInfo build() {
        com.qanydesk.protocol.ProtocolOuter.ScReplyInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.qanydesk.protocol.ProtocolOuter.ScReplyInfo buildPartial() {
        com.qanydesk.protocol.ProtocolOuter.ScReplyInfo result = new com.qanydesk.protocol.ProtocolOuter.ScReplyInfo(this);
        result.success_ = success_;
        result.registerId_ = registerId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qanydesk.protocol.ProtocolOuter.ScReplyInfo) {
          return mergeFrom((com.qanydesk.protocol.ProtocolOuter.ScReplyInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qanydesk.protocol.ProtocolOuter.ScReplyInfo other) {
        if (other == com.qanydesk.protocol.ProtocolOuter.ScReplyInfo.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (!other.getRegisterId().isEmpty()) {
          registerId_ = other.registerId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qanydesk.protocol.ProtocolOuter.ScReplyInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qanydesk.protocol.ProtocolOuter.ScReplyInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 1;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 1;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object registerId_ = "";
      /**
       * <code>string registerId = 2;</code>
       * @return The registerId.
       */
      public java.lang.String getRegisterId() {
        java.lang.Object ref = registerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          registerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string registerId = 2;</code>
       * @return The bytes for registerId.
       */
      public com.google.protobuf.ByteString
          getRegisterIdBytes() {
        java.lang.Object ref = registerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          registerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string registerId = 2;</code>
       * @param value The registerId to set.
       * @return This builder for chaining.
       */
      public Builder setRegisterId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        registerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string registerId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRegisterId() {
        
        registerId_ = getDefaultInstance().getRegisterId();
        onChanged();
        return this;
      }
      /**
       * <code>string registerId = 2;</code>
       * @param value The bytes for registerId to set.
       * @return This builder for chaining.
       */
      public Builder setRegisterIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        registerId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protocol.ScReplyInfo)
    }

    // @@protoc_insertion_point(class_scope:Protocol.ScReplyInfo)
    private static final com.qanydesk.protocol.ProtocolOuter.ScReplyInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qanydesk.protocol.ProtocolOuter.ScReplyInfo();
    }

    public static com.qanydesk.protocol.ProtocolOuter.ScReplyInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ScReplyInfo>
        PARSER = new com.google.protobuf.AbstractParser<ScReplyInfo>() {
      @java.lang.Override
      public ScReplyInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ScReplyInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ScReplyInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ScReplyInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.qanydesk.protocol.ProtocolOuter.ScReplyInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocol_Protocol_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocol_Protocol_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocol_CsHostInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocol_CsHostInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocol_ScReplyInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocol_ScReplyInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Protocol.proto\022\010Protocol\"z\n\010Protocol\022\014" +
      "\n\004type\030\001 \001(\t\022*\n\ncsHostInfo\030\002 \001(\0132\024.Proto" +
      "col.CsHostInfoH\000\022,\n\013scReplyInfo\030\003 \001(\0132\025." +
      "Protocol.ScReplyInfoH\000B\006\n\004body\"E\n\nCsHost" +
      "Info\022\r\n\005cpuId\030\001 \001(\t\022\024\n\014diskDeviceId\030\002 \001(" +
      "\t\022\022\n\nmacAddress\030\003 \001(\t\"2\n\013ScReplyInfo\022\017\n\007" +
      "success\030\001 \001(\010\022\022\n\nregisterId\030\002 \001(\tB(\n\025com" +
      ".qanydesk.protocolB\rProtocolOuterH\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Protocol_Protocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Protocol_Protocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocol_Protocol_descriptor,
        new java.lang.String[] { "Type", "CsHostInfo", "ScReplyInfo", "Body", });
    internal_static_Protocol_CsHostInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Protocol_CsHostInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocol_CsHostInfo_descriptor,
        new java.lang.String[] { "CpuId", "DiskDeviceId", "MacAddress", });
    internal_static_Protocol_ScReplyInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Protocol_ScReplyInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocol_ScReplyInfo_descriptor,
        new java.lang.String[] { "Success", "RegisterId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
