// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QMessage.proto

package com.qanydesk.protocol;

public final class QMessageOuter {
  private QMessageOuter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:QMessage.QMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 type = 1;</code>
     * @return The type.
     */
    int getType();

    /**
     * <code>string cpuId = 2;</code>
     * @return The cpuId.
     */
    java.lang.String getCpuId();
    /**
     * <code>string cpuId = 2;</code>
     * @return The bytes for cpuId.
     */
    com.google.protobuf.ByteString
        getCpuIdBytes();
  }
  /**
   * <pre>
   * C++的头文件名取第一个message名
   * </pre>
   *
   * Protobuf type {@code QMessage.QMessage}
   */
  public static final class QMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:QMessage.QMessage)
      QMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QMessage.newBuilder() to construct.
    private QMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QMessage() {
      cpuId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new QMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              type_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              cpuId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qanydesk.protocol.QMessageOuter.internal_static_QMessage_QMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qanydesk.protocol.QMessageOuter.internal_static_QMessage_QMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qanydesk.protocol.QMessageOuter.QMessage.class, com.qanydesk.protocol.QMessageOuter.QMessage.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>int32 type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }

    public static final int CPUID_FIELD_NUMBER = 2;
    private volatile java.lang.Object cpuId_;
    /**
     * <code>string cpuId = 2;</code>
     * @return The cpuId.
     */
    @java.lang.Override
    public java.lang.String getCpuId() {
      java.lang.Object ref = cpuId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cpuId_ = s;
        return s;
      }
    }
    /**
     * <code>string cpuId = 2;</code>
     * @return The bytes for cpuId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCpuIdBytes() {
      java.lang.Object ref = cpuId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cpuId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeInt32(1, type_);
      }
      if (!getCpuIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cpuId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (!getCpuIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cpuId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qanydesk.protocol.QMessageOuter.QMessage)) {
        return super.equals(obj);
      }
      com.qanydesk.protocol.QMessageOuter.QMessage other = (com.qanydesk.protocol.QMessageOuter.QMessage) obj;

      if (getType()
          != other.getType()) return false;
      if (!getCpuId()
          .equals(other.getCpuId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + CPUID_FIELD_NUMBER;
      hash = (53 * hash) + getCpuId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qanydesk.protocol.QMessageOuter.QMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qanydesk.protocol.QMessageOuter.QMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qanydesk.protocol.QMessageOuter.QMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qanydesk.protocol.QMessageOuter.QMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qanydesk.protocol.QMessageOuter.QMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qanydesk.protocol.QMessageOuter.QMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qanydesk.protocol.QMessageOuter.QMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qanydesk.protocol.QMessageOuter.QMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qanydesk.protocol.QMessageOuter.QMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qanydesk.protocol.QMessageOuter.QMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qanydesk.protocol.QMessageOuter.QMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qanydesk.protocol.QMessageOuter.QMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qanydesk.protocol.QMessageOuter.QMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * C++的头文件名取第一个message名
     * </pre>
     *
     * Protobuf type {@code QMessage.QMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:QMessage.QMessage)
        com.qanydesk.protocol.QMessageOuter.QMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qanydesk.protocol.QMessageOuter.internal_static_QMessage_QMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qanydesk.protocol.QMessageOuter.internal_static_QMessage_QMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qanydesk.protocol.QMessageOuter.QMessage.class, com.qanydesk.protocol.QMessageOuter.QMessage.Builder.class);
      }

      // Construct using com.qanydesk.protocol.QMessageOuter.QMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        cpuId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qanydesk.protocol.QMessageOuter.internal_static_QMessage_QMessage_descriptor;
      }

      @java.lang.Override
      public com.qanydesk.protocol.QMessageOuter.QMessage getDefaultInstanceForType() {
        return com.qanydesk.protocol.QMessageOuter.QMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.qanydesk.protocol.QMessageOuter.QMessage build() {
        com.qanydesk.protocol.QMessageOuter.QMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.qanydesk.protocol.QMessageOuter.QMessage buildPartial() {
        com.qanydesk.protocol.QMessageOuter.QMessage result = new com.qanydesk.protocol.QMessageOuter.QMessage(this);
        result.type_ = type_;
        result.cpuId_ = cpuId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qanydesk.protocol.QMessageOuter.QMessage) {
          return mergeFrom((com.qanydesk.protocol.QMessageOuter.QMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qanydesk.protocol.QMessageOuter.QMessage other) {
        if (other == com.qanydesk.protocol.QMessageOuter.QMessage.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.getCpuId().isEmpty()) {
          cpuId_ = other.cpuId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qanydesk.protocol.QMessageOuter.QMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qanydesk.protocol.QMessageOuter.QMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object cpuId_ = "";
      /**
       * <code>string cpuId = 2;</code>
       * @return The cpuId.
       */
      public java.lang.String getCpuId() {
        java.lang.Object ref = cpuId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cpuId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cpuId = 2;</code>
       * @return The bytes for cpuId.
       */
      public com.google.protobuf.ByteString
          getCpuIdBytes() {
        java.lang.Object ref = cpuId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cpuId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cpuId = 2;</code>
       * @param value The cpuId to set.
       * @return This builder for chaining.
       */
      public Builder setCpuId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cpuId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cpuId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCpuId() {
        
        cpuId_ = getDefaultInstance().getCpuId();
        onChanged();
        return this;
      }
      /**
       * <code>string cpuId = 2;</code>
       * @param value The bytes for cpuId to set.
       * @return This builder for chaining.
       */
      public Builder setCpuIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cpuId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:QMessage.QMessage)
    }

    // @@protoc_insertion_point(class_scope:QMessage.QMessage)
    private static final com.qanydesk.protocol.QMessageOuter.QMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qanydesk.protocol.QMessageOuter.QMessage();
    }

    public static com.qanydesk.protocol.QMessageOuter.QMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QMessage>
        PARSER = new com.google.protobuf.AbstractParser<QMessage>() {
      @java.lang.Override
      public QMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.qanydesk.protocol.QMessageOuter.QMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QMessage_QMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QMessage_QMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016QMessage.proto\022\010QMessage\"\'\n\010QMessage\022\014" +
      "\n\004type\030\001 \001(\005\022\r\n\005cpuId\030\002 \001(\tB(\n\025com.qanyd" +
      "esk.protocolB\rQMessageOuterH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_QMessage_QMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_QMessage_QMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QMessage_QMessage_descriptor,
        new java.lang.String[] { "Type", "CpuId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
